spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        default-requeue-rejected: true
        max-concurrency: 5
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 4
          multiplier: 2
          max-interval: 10s
